String.toLocaleString({
	"en": {
		"%gearing": "Gearing",
		"%chainrings": "Chainrings",
		"%sprockets": "Sprockets", 
		"%wheel_size": "Tire Size",
		"%circumference": "tire circumference",
		"%display": "Display",
		"%cadence": "Cadence",
		"%chain_angle": "Chain Angle <",
		"%units": "Units",
		"%compare": "Compare two Setups",
		"%derailleurs": "Derailleurs",
		"%teeth": "Teeth",
		"%development": "Development",
		"%ratio": "Ratio",
		"%speed": "Speed",
		"%gear_step": "Gear Step/%"
	},
	"fr": {
		"%gearing": "Moyeu",
		"%chainrings": "Plateaux",
		"%sprockets": "Pignons",
		"%wheel_size": "Pneus",
		"%circumference": "circumference",
		"%display": "Display",
		"%cadence": "Cadence",
		"%chain_angle": "Angle Chaîne <",
		"%units": "Unité",
		"%compare": "Comparer",
		"%derailleurs": "Derailleurs",
		"%teeth": "Dents",
		"%development": "Developpement",
		"%ratio": "Ratio",
		"%speed": "Vitesse",
		"%gear_step": "Différence/%"
	}, 
	"de": {
		"%gearing": "Schaltung",
		"%chainrings": "Kettenblätter",
		"%sprockets": "Ritzel",
		"%wheel_size": "Reifengröße",
		"%circumference": "Radumfang",
		"%display": "Anzeige", 
		"%cadence": "Trittfreq.",
		"%chain_angle": "Kettenwinkel <",
		"%units": "Einheit",
		"%compare": "Vergleich",
		"%derailleurs": "Kettenschaltung",
		"%teeth": "Zahnzahl",
		"%development": "Entfaltung",
		"%ratio": "Übersetzung",
		"%speed": "Geschwindigkeit",
		"%gear_step": "Gangsprung/%"
	},
	"hu": {
		"%gearing": "Áttételek",
		"%chainrings": "Első lánck.",
		"%sprockets": "Hátsó lánck.",
		"%wheel_size": "Kerékméret /mm",
		"%circumference": "vagy kerület",
		"%display": "Display",
		"%cadence": "Pedálford.",
		"%chain_angle": "Láncelhajlás <",
		"%units": "Egységek",
		"%compare": "Összehasonlítás",
		"%derailleurs": "Láncváltós",
		"%teeth": "Fogszám",
		"%development": "Haladás",
		"%ratio": "Fogarány",
		"%speed": "Sebesség",
		"%gear_step": "Áttételugrás/%"
	}

});