String.toLocaleString({
	"en": {
	    "title":"www.gear-calculator.com",
		"%gearing": "Gearing",
		"%chainrings": "Chainrings",
		"%sprockets": "Sprockets", 
		"%wheel_size": "Tire Size",
		"%circumference": "tire circumference",
		"%display": "Display",
		"%cadence": "Cadence",
		"%chain_angle": "Chain Angle <",
		"%units": "Units",
		"%compare": "Compare two Setups",
		"%derailleurs": "Derailleurs",
		"%teeth": "Teeth",
		"%development": "Development",
		"%ratio": "Ratio",
		"%speed": "Speed",
		"%gear_step": "Gear Step/%",
		"%mail": "info@ritzelrechner.de",
		"%tt_compare": "Click to compare to display a second gearing set up",
		"%tt_mail": "send comments and feedback to this adress",
		"%tt_moveCw": "move the chainring to select another number of teeth",
		"%tt_moveSp": "move the sprocket to select another number of teeth",
		"%tt_wheel_size": "select the wheel size or type in the circumference in mm directly",
		"%tt_display": "display the numerical values directly",
		"%tt_units": "choose between SI (meter, km/h) and US customary (inch, mile) units",
		"%tt_url": "use this URL to point to the currently selected gearing e.g. for referencing it in online discussions etc.",
		"%tt_chain_angle": "sets the maximum allowed chain angle (approx. in degrees). Combinations where the chain runs too diagonal and should not be used are greyed out in the graphics."
	},
	"fr": {
	    "%title":"www.gear-calculator.com",
		"%gearing": "Moyeu",
		"%chainrings": "Plateaux",
		"%sprockets": "Pignons",
		"%wheel_size": "Pneus",
		"%circumference": "circumference",
		"%display": "Display",
		"%cadence": "Cadence",
		"%chain_angle": "Angle Chaîne <",
		"%units": "Unité",
		"%compare": "Comparer",
		"%derailleurs": "Derailleurs",
		"%teeth": "Dents",
		"%development": "Developpement",
		"%ratio": "Ratio",
		"%speed": "Vitesse",
		"%gear_step": "Différence/%",
		"%mail": "info@ritzelrechner.de",
		"%tt_compare": "Click to display a second gearing set up",
		"%tt_mail":"send comments and feedback to this adress",
		"%tt_moveCw": "move the chainring to select another number of teeth",
		"%tt_moveSp": "move the sprocket to select another number of teeth",
		"%tt_wheel_size":"select the wheel size or type in the circumference in mm directly",
		"%tt_display": "display the numerical values directly",
		"%tt_units": "choose between SI (meter, km/h) and US customary (inch, mile) units",
		"%tt_url": "use this URL to point to the currently selected gearing e.g. for referencing it in online discussions etc.",
		"%tt_chain_angle": "sets the maximum allowed chain angle (approx. in degrees). Combinations where the chain runs too diagonal and should not be used are greyed out in the graphics."
	}, 
	"de": {
	    "%title":"www.ritzelrechner.de",
		"%gearing": "Schaltung",
		"%chainrings": "Kettenblätter",
		"%sprockets": "Ritzel",
		"%wheel_size": "Reifengröße",
		"%circumference": "Radumfang",
		"%display": "Anzeige", 
		"%cadence": "Trittfreq.",
		"%chain_angle": "Kettenwinkel <",
		"%units": "Einheit",
		"%compare": "Vergleich",
		"%derailleurs": "Kettenschaltung",
		"%teeth": "Zahnzahl",
		"%development": "Entfaltung",
		"%ratio": "Übersetzung",
		"%speed": "Geschwindigkeit",
		"%gear_step": "Gangsprung/%",
		"%mail": "info@ritzelrechner.de",
		"%tt_compare": "Zeigt zum Vergleich die Grafik einer zweiten Schaltungsvariante",
		"%tt_mail":"Kommentare und Anregungen sind erwünscht",
		"%tt_moveCw": "Bewege das Ritzel auf der Skala um eine andere Zahnzahl auszuwählen",
		"%tt_moveSp": "Bewege das Kettenblatt auf der Skala, um eine andere Zahmzahl auszuwählen",
		"%tt_wheel_size":"Wähle eine gängige Reifengröße aus oder gebe den Umfang direkt ein",
		"%tt_display": "Zeigt die ausgewählten Werte zusätzlich numerisch an",
		"%tt_units": "Auswahl zwischen SI (meter, km/h) und US (inch, mile) Einheiten",
		"%tt_url": "Diese URL zeigt direkt die gerade ausgewählte Schaltung an und kann z.B. als Referenz in Online Diskussionen verwendet werden",
		"%tt_chain_angle": "Setzt den maximal erlaubten Kettenschräglauf (näherungsweise in Grad). Kombinationen, bei denen die Kette schräger läuft als dieser Wert, werden in der Grafik ausgegraut."
	},
	"hu": {
	    "%title":"www.gear.calculator.com",
		"%gearing": "Áttételek",
		"%chainrings": "Első lánck.",
		"%sprockets": "Hátsó lánck.",
		"%wheel_size": "Kerékméret /mm",
		"%circumference": "vagy kerület",
		"%display": "Display",
		"%cadence": "Pedálford.",
		"%chain_angle": "Láncelhajlás <",
		"%units": "Egységek",
		"%compare": "Összehasonlítás",
		"%derailleurs": "Láncváltós",
		"%teeth": "Fogszám",
		"%development": "Haladás",
		"%ratio": "Fogarány",
		"%speed": "Sebesség",
		"%gear_step": "Áttételugrás/%",
		"%mail": "info@ritzelrechner.de (Magyar nyelvű megjegyzések vagy javaslatok: nagy.elte@gmail.com)",
		"%tt_compare": "Click to compare to display a second gearing set up",
		"%tt_mail":"send comments and feedback to this adress",
		"%tt_moveCw": "move the chainring to select another number of teeth",
		"%tt_moveSp": "move the sprocket to select another number of teeth",
		"%tt_wheel_size":"select the wheel size or type in the circumference in mm directly",
		"%tt_display": "display the numerical values directly",
		"%tt_units": "choose between SI (meter, km/h) and US customary (inch, mile) units",
		"%tt_url": "use this URL to point to the currently selected gearing e.g. for referencing it in online discussions etc.",
		"%tt_chain_angle": "sets the maximum allowed chain angle (approx. in degrees). Combinations where the chain runs too diagonal and should not be used are greyed out in the graphics."
	}

});