String.toLocaleString({
	"en": {
	    "title":"Bicycle Gear Calculator",
		"%gearing": "Gearing",
		"%chainrings": "Chainrings",
		"%sprockets": "Sprockets", 
		"%wheel_size": "Tire Size",
		"%circumference": "tire circumference",
		"%display": "Display",
		"%cadence": "Cadence",
		"%chain_angle": "Chain Angle <",
		"%units": "Units",
		"%compare": "Compare two Setups",
		"%derailleurs": "Derailleurs",
		"%custom": "Custom",
		"%teeth": "Teeth",
		"%development": "Development",
		"%ratio": "Ratio",
		"%speed": "Speed",
		"%gear_step": "Gear Step/%",
		"%mail": "info@ritzelrechner.de",
		"%torque_warning": "High Torque!",
		"%tt_compare": "Click to compare to display a second gearing set up",
		"%tt_mail": "send comments and feedback to this adress",
		"%tt_moveCw": "move the chainring to select another number of teeth",
		"%tt_moveSp": "move the sprocket to select another number of teeth",
		"%tt_wheel_size": "select the wheel size or type in the circumference in mm directly",
		"%tt_display": "display the numerical values directly",
		"%tt_units": "choose between SI (meter, km/h) and US customary (inch, mile) units",
		"%tt_url": "use this URL to point to the currently selected gearing e.g. for referencing it in online discussions etc.",
		"%tt_chain_angle": "sets the maximum allowed chain angle (approx. in degrees). Combinations where the chain runs too diagonal and should not be used are greyed out in the graphics."
	},
	"es": {
		"%title":"Calculador de desarrollos de bicicleta",
		"%gearing": "Cambios",
		"%chainrings": "Platos",
		"%sprockets": "Piñones", 
		"%wheel_size": "Cubierta",
		"%circumference": "Circunferencia de la cubierta",
		"%display": "Mostrar",
		"%cadence": "Cadencia",
		"%chain_angle": "Áng. de cadena <",
		"%units": "Unidades",
		"%compare": "Comparar dos configuraciones",
		"%derailleurs": "Desviadores",
		"%custom": "Personalizado",
		"%teeth": "Dientes",
		"%development": "Desarrollo",
		"%ratio": "Relación",
		"%speed": "Velocidad",
		"%gear_step": "Variación desarrollo/%",
		"%mail": "info@ritzelrechner.de",
		"%torque_warning": "¡Par alto!",
		"%tt_compare": "Cliquea para mostrar y comparar una seegunda configuración",
		"%tt_mail": "Haznos llegar tus comentarios y sugerencias",
		"%tt_moveCw": "Desplaza el plato para seleccionar otro número de dientes",
		"%tt_moveSp": "Desplaza el piñón para seleccionar otro número de dientes",
		"%tt_wheel_size": "Selecciona el tamaño de rueda o escribe directamente su circunferencia en mm.",
		"%tt_display": "Mostrar directamente los valores numéricos",
		"%tt_units": "Escoge las unidades entre S.I. (metros, km/h) o US/imperial (pulgadas, milla)",
		"%tt_url": "Usa esta URL para apuntar a la configuración seleccionada en este momento (por ejemplo, para referirte a ella en foros online, etc)",
		"%tt_chain_angle": "Configura el mayor ángulo de cadena permitido (aprox. en grados). Las combinaciones en las que la cadena se mueve demasiado en diagonal y no deben ser usadas aparecen en gris en los gráficos."
		},
	"fr": {
	    "%title":"Calculateur de Derailleurs",
		"%gearing": "Moyeu",
		"%chainrings": "Plateaux",
		"%sprockets": "Pignons",
		"%wheel_size": "Pneus",
		"%circumference": "circumference",
		"%display": "Display",
		"%cadence": "Cadence",
		"%chain_angle": "Angle Chaîne <",
		"%units": "Unité",
		"%compare": "Comparer",
		"%derailleurs": "Derailleurs",
		"%custom": "Custom",
		"%teeth": "Dents",
		"%development": "Developpement",
		"%ratio": "Ratio",
		"%speed": "Vitesse",
		"%gear_step": "Différence/%",
		"%mail": "info@ritzelrechner.de",
		"%torque_warning": "High Torque!",
		"%tt_compare": "Click to display a second gearing set up",
		"%tt_mail":"send comments and feedback to this adress",
		"%tt_moveCw": "move the chainring to select another number of teeth",
		"%tt_moveSp": "move the sprocket to select another number of teeth",
		"%tt_wheel_size":"select the wheel size or type in the circumference in mm directly",
		"%tt_display": "display the numerical values directly",
		"%tt_units": "choose between SI (meter, km/h) and US customary (inch, mile) units",
		"%tt_url": "use this URL to point to the currently selected gearing e.g. for referencing it in online discussions etc.",
		"%tt_chain_angle": "sets the maximum allowed chain angle (approx. in degrees). Combinations where the chain runs too diagonal and should not be used are greyed out in the graphics."
	}, 
	"de": {
	    "%title":"Der Ritzelrechner",
		"%gearing": "Schaltung",
		"%chainrings": "Kettenblätter",
		"%sprockets": "Ritzel",
		"%wheel_size": "Reifengröße",
		"%circumference": "Radumfang",
		"%display": "Anzeige", 
		"%cadence": "Trittfreq.",
		"%chain_angle": "Kettenwinkel <",
		"%units": "Einheit",
		"%compare": "Vergleich",
		"%derailleurs": "Kettenschaltung",
		"%custom": "Custom",
		"%teeth": "Zahnzahl",
		"%development": "Entfaltung",
		"%ratio": "Übersetzung",
		"%speed": "Geschwindigkeit",
		"%gear_step": "Gangsprung/%",
		"%mail": "info@ritzelrechner.de",
		"%torque_warning": "Hohes Drehmoment!",
		"%tt_compare": "Zeigt zum Vergleich die Grafik einer zweiten Schaltungsvariante",
		"%tt_mail":"Kommentare und Anregungen sind erwünscht",
		"%tt_moveCw": "Bewege das Ritzel auf der Skala um eine andere Zahnzahl auszuwählen",
		"%tt_moveSp": "Bewege das Kettenblatt auf der Skala, um eine andere Zahmzahl auszuwählen",
		"%tt_wheel_size":"Wähle eine gängige Reifengröße aus oder gebe den Umfang direkt in mm ein",
		"%tt_display": "Zeigt die ausgewählten Werte zusätzlich numerisch an",
		"%tt_units": "Auswahl zwischen SI (meter, km/h) und US (inch, mile) Einheiten",
		"%tt_url": "Diese URL zeigt direkt die gerade ausgewählte Schaltung an und kann z.B. als Referenz in Online Diskussionen verwendet werden",
		"%tt_chain_angle": "Setzt den maximal erlaubten Kettenschräglauf (näherungsweise in Grad). Kombinationen, bei denen die Kette schräger läuft als dieser Wert, werden in der Grafik ausgegraut."
	},
	"hu": {
	    "%title":"Mindentudó áttételkalkulátor",
		"%gearing": "Áttételek",
		"%chainrings": "Fogszám elöl",
		"%sprockets": "Fogszám hátul",
		"%wheel_size": "Kerékméret",
		"%circumference": "Kerékkerület/mm",
		"%display": "Kijelzendő",
		"%cadence": "Fordulat/perc",
		"%chain_angle": "Láncelhajlás <",
		"%units": "Egységválasztás",
		"%compare": "Összehasonlítás be/ki",
		"%derailleurs": "Láncváltós",
		"%custom": "Egyedi",
		"%teeth": "Fogszám",
		"%development": "Haladás",
		"%ratio": "Fogszámarány",
		"%speed": "Sebesség",
		"%gear_step": "Áttételugrás/%",
		"%mail": "info@ritzelrechner.de (Magyar nyelvű megjegyzések: nagysandor.eu | nagy.elte@gmail.com)",
		"%torque_warning": "Túl nagy nyomaték!",
		"%tt_compare": "Kattintásra másolat készül a beállításról, melyet változtatgathatsz. Újabb kattintásra eltűnik az eredeti (felső) változat, és marad az új.",
		"%tt_mail":"Javaslatokat szívesen fogadunk.",
		"%tt_moveCw": "Mozgasd az első lánckereket, ha elöl más fogszámot szeretnél!",
		"%tt_moveSp": "Mozgasd a hátsó lánckereket, ha hátul más fogszámot szeretnél!",
		"%tt_wheel_size":"Válassz egy kerékméretet a listáról, vagy írd be közvetlenül a kerék mm-ben mért/kiszámolt kerületét!",
		"%tt_display": "Jelenítsd meg a diagramon a kiválasztott mennyiség számértékét is!",
		"%tt_units": "Válassz az SI (méter, km/h) és az angolszász (inch, mile) egységek között!",
		"%tt_url": "Ezen a webcímen találod azt az áttételezést, amely ebben a pillanatban látszik a képernyődön. Ha kimásolod, bármikor felidézheted magadnak, ha kell, ill. megoszthatod másokkal is.",
		"%tt_chain_angle": "Itt állíthatod be (kb. fokban megadva), hogy maximum mekkora oldalirányú láncelhajlást tartasz elfogadhatónak. Azok a lánckerék-kombinációk, amelyeknél ennél nagyobb az elhajlás (túl ferdén fut a lánc) kihalványítva látszanak a diagramon."
	}

});